version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: 'Say hello'
          command: 'echo Hello, World!'

  sonarqube:
    working_directory: ~/build
    docker:
      - image: openjdk:17
    resource_class: small
    steps:
      - run:
          name: Install unzip and SonarQube Scanner
          command: |
            apt-get update && apt-get install -y unzip
            curl -Lo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner.zip -d $HOME
            export PATH="$HOME/sonar-scanner-4.6.2.2472-linux/bin:$PATH"
      - run: find .
      - attach_workspace:
          at: ~/workspace
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-main}"
          echo "Sonar branch value is: " $SONAR_BRANCH
          echo "Sonar org value is : "$SONAR_ORG
          $HOME/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
          -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
          -Dsonar.organization="$SONAR_ORG" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.exclusions="**/android/**,**/ios/**" \
          -Dsonar.login="$SONAR_TOKEN" \
          -Dsonar.branch.name="$SONAR_BRANCH" \
          -Dsonar.sources="."

# Orchestrate jobs using workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
